<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_Recommend_playerId__28250694--23_html5_api</name>
   <tag></tag>
   <elementGuidId>c3ae3fa8-58fb-4f0d-99be-e474619c698e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#playerId__28250694--23_html5_api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='playerId__28250694--23_html5_api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>f7b6912c-70a8-4647-aeed-ba4ac4140041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>a5ed246a-31c8-40a2-b92c-ba1898320fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>playerId__28250694--23_html5_api</value>
      <webElementGuid>31dfabbf-215a-449c-99ef-e501e69b27ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a325257e-f6af-4ea0-86a9-dd0561343c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>controlslist</name>
      <type>Main</type>
      <value>nodownload</value>
      <webElementGuid>282c7300-5213-4521-8683-b4b4e2e45e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webboost_found_paused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98fddc7c-f08e-4d2a-b206-a7076f68d19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webboost_processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58246406-380c-444a-a9d8-3971fde82915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>52e8b510-dca1-47b4-ae35-68eea6160ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://cognizant.udemy.com/0dda1b39-d579-49a5-97f5-b081ca26b38e</value>
      <webElementGuid>b40aca50-270e-479a-a78a-cc68f2a4943b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webboost_videoid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d5019d1-725c-4cbf-9b04-1d61ecf2f959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webboost_userplayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0ad22a0-9480-4083-9b98-89dd9259a83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;playerId__28250694--23_html5_api&quot;)</value>
      <webElementGuid>667c30d3-6dc8-47d9-bf5e-ce48417dc0b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='playerId__28250694--23_html5_api']</value>
      <webElementGuid>4adc35b9-c284-47fd-9329-6b317b8e3314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='playerId__28250694--23']/video</value>
      <webElementGuid>e2667b49-5b67-48a4-b9ef-1ca54233406a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>cc4d7774-4b2c-40b1-a012-078cd595e6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'playerId__28250694--23_html5_api' and @src = 'blob:https://cognizant.udemy.com/0dda1b39-d579-49a5-97f5-b081ca26b38e']</value>
      <webElementGuid>63c23d40-7484-4521-9748-4e5c74ffc1de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
