<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Desktop Testing</name>
   <tag></tag>
   <elementGuidId>b42cd814-22a5-47f1-9574-646953402ca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.brand-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_widget_1641447121835']/div/div/div/div/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f5c6d509-25a0-4dd1-bd35-7e2c44b97944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-heading</value>
      <webElementGuid>0b0d7858-1666-4b2e-9802-3c5920023765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desktop Testing</value>
      <webElementGuid>98a31f4b-0c97-4b29-b3e2-b8de8150bd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_widget_1641447121835&quot;)/div[@class=&quot;testing_banner_mdl gradient&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/h1[@class=&quot;brand-heading&quot;]</value>
      <webElementGuid>293a9d36-f9bd-43dc-8ffd-1dae5dc13d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_widget_1641447121835']/div/div/div/div/div/div/h1</value>
      <webElementGuid>05eafeeb-5a86-47ca-93c0-70b7fe4682cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Now'])[1]/following::h1[1]</value>
      <webElementGuid>7738885f-7ea8-4c07-9e34-710729f1ab94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[2]/following::h1[1]</value>
      <webElementGuid>345fede6-bdb7-49fe-aa29-0f1c25194599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Desktop Testing'])[1]/preceding::h1[1]</value>
      <webElementGuid>abf003d3-57d4-46f2-856a-4569d7b8d685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Demo'])[1]/preceding::h1[1]</value>
      <webElementGuid>40263bb3-7875-4488-950d-a6f407094c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2df3190d-0676-419d-bfe0-9c51e824be32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Desktop Testing' or . = 'Desktop Testing')]</value>
      <webElementGuid>19575e7e-c2d6-4a8f-8c64-98f4c435c79c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
