<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Automation</name>
   <tag></tag>
   <elementGuidId>f9f7764a-098d-4409-985a-dbf20792b0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_list > li > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='filter_list']/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c6a5886-5d18-4eba-94c9-7682e99a0313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-value</name>
      <type>Main</type>
      <value>.automation</value>
      <webElementGuid>87a4a79e-5470-4368-a5e5-3c9753d7d5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation</value>
      <webElementGuid>4d221f30-8afe-4ddf-b4bf-747573120f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_list&quot;)/li[1]/div[1]</value>
      <webElementGuid>e554b6a1-370c-4fe7-82a8-5cd1787af6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames and Window Dummy Testing Site -_484b9f/iframe_br</value>
      <webElementGuid>5eee0536-daf9-4f35-aa88-05ad9540142a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='filter_list']/li/div</value>
      <webElementGuid>fee6d280-763d-4322-b1bd-192270ded10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[1]</value>
      <webElementGuid>01d3ff78-4fd0-4117-9ae2-2a170fbb1abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trainings'])[2]/following::div[5]</value>
      <webElementGuid>9e82dbaf-6107-4636-bbf5-a95657cbab0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance Testing'])[1]/preceding::div[1]</value>
      <webElementGuid>6707b13b-88ff-47e5-8899-e3a53487d611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Testing'])[1]/preceding::div[2]</value>
      <webElementGuid>387b4c61-7fcd-42fa-a339-ca1774f4dd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automation']/parent::*</value>
      <webElementGuid>ef3222d8-a0f1-4715-8960-643cd2487b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li/div</value>
      <webElementGuid>132096d4-8cc4-4ca6-94b6-667816883430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Automation' or . = 'Automation')]</value>
      <webElementGuid>57dbf0ab-538e-4be1-b555-4f0896b631e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
