<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pinterest_s</name>
   <tag></tag>
   <elementGuidId>38206632-50aa-4b41-8c72-28114539f9d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='s']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92f8f61e-3cc1-4adc-bd14-90e845e357cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>217dfc04-5ff8-40ec-9aa7-ea6d459aafa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>28b4645d-58f8-46ab-bff4-b30690460189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10c8030b-123c-496e-84e6-dbf1449697cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>c2fedb12-9efd-499d-a268-c5d5a22ad86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s&quot;)</value>
      <webElementGuid>0207e606-9cc6-44bf-9616-75314333880f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames and Window Dummy Testing Site -_484b9f/iframe_br</value>
      <webElementGuid>42761c92-1c97-4189-9c26-74f57e2514d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='s']</value>
      <webElementGuid>7ea6b902-317d-47d0-8080-5f4c5cf3e5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subheader']/div/div/div/form/input</value>
      <webElementGuid>bdb01430-e5ef-4cae-9658-0912e36280bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5af81f0d-1a17-4a39-a0c8-ec74b9a2184a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 's' and @id = 's' and @type = 'text' and @placeholder = 'Search...']</value>
      <webElementGuid>c85e0a91-aad1-4336-85d4-1ebf0863c5c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
