<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave</name>
   <tag></tag>
   <elementGuidId>ff8b48b6-e86b-4715-a7c8-79dcfb6f0f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_leave_viewLeaveModule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_leave_viewLeaveModule']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77d240f5-8420-4682-a1cd-9600ec1198a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/leave/viewLeaveModule</value>
      <webElementGuid>4bfa5f44-5673-4457-95a7-56963efe38a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_leave_viewLeaveModule</value>
      <webElementGuid>a04ce007-c393-4a5b-accc-89575f7f4c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstLevelMenu</value>
      <webElementGuid>0de01374-e3aa-4fa6-b791-61c7248e0e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave</value>
      <webElementGuid>92335e4d-0aa6-4255-a10e-63d328ff770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_leave_viewLeaveModule&quot;)</value>
      <webElementGuid>793b3218-f785-4f61-913e-0192ef55b82c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_leave_viewLeaveModule']</value>
      <webElementGuid>55d67382-8289-4acb-83a3-9b1a48e51952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[3]/a</value>
      <webElementGuid>d960ad85-cfef-4e09-96b4-b3ec4c9cab6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::a[1]</value>
      <webElementGuid>1cf669a7-9df3-4de6-a7af-df9c2fdd1f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Employee'])[1]/following::a[2]</value>
      <webElementGuid>1a9c19bc-7648-4892-99aa-0c1f9d77be31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::a[1]</value>
      <webElementGuid>76cf9ee3-ed31-401f-97d5-6a5b701dda70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/leave/viewLeaveModule')]</value>
      <webElementGuid>43f6da38-ac37-4fb8-a66a-b8ec76d819ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>598d9a4c-751c-40df-a841-9725601fcfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/leave/viewLeaveModule' and @id = 'menu_leave_viewLeaveModule' and (text() = 'Leave' or . = 'Leave')]</value>
      <webElementGuid>69209252-83bc-47b9-bb43-2bcd40ebea3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
